# Generated by Django 4.0.6 on 2024-01-28 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='referral_code',
        ),
        migrations.AddField(
            model_name='order',
            name='accomodation_required',
            field=models.CharField(default='No', max_length=100),
        ),
    ]
