# Generated by Django 4.0.6 on 2024-01-31 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_orders', '0004_alter_order_accomodation_required'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='accomodation_required',
        ),
        migrations.RemoveField(
            model_name='order',
            name='year',
        ),
    ]
