# Generated by Django 4.0.6 on 2023-06-20 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team_members',
            name='photo',
            field=models.ImageField(default='', upload_to='photos/team'),
        ),
    ]
