# Generated by Django 4.0.6 on 2023-06-21 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waves_events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='one_liner_description',
            field=models.TextField(blank=True, max_length=200),
        ),
    ]
